#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Linux" ]; then
    echo "Installing other packages"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
else
	echo "Other OS: $system_type"
fi

